server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.154.129
  rabbitmq:
    host: 192.168.154.129
    virtual-host: /qinhan
    username: qinhan
    password: qinhan

auth:
  jwt:
    publicKeyPath: D:\\develop\\Code\\workspace-idea\\tmp\\rsa.pub
    cookieName: GMALL_TOKEN
